In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('flipkart_sales.csv', encoding='latin1')
df.rename(columns={'InvoiceNo':'OrderID','UnitPrice':'Price','Country':'City'}, inplace=True)
df.head()

ModuleNotFoundError: No module named 'pandas'

In [ ]:
df = pd.read_csv('flipkart_sales.csv', encoding='latin1')
df.rename(columns={'InvoiceNo':'OrderID','UnitPrice':'Price','Country':'City'}, inplace=True)

In [2]:
!which python

'which' is not recognized as an internal or external command,
operable program or batch file.

In [3]:
!{sys.executable} -m pip install pandas matplotlib

'{sys.executable}' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
!where python

c:\Python312\python.exe
C:\Users\karan\AppData\Local\Microsoft\WindowsApps\python.exe

In [5]:
!where pip

C:\Python312\Scripts\pip.exe

In [6]:
!{sys.executable} -m pip install pandas matplotlib

'{sys.executable}' is not recognized as an internal or external command,
operable program or batch file.

In [7]:
import sys
!"{sys.executable}" -m pip install pandas matplotlib

Collecting pandas
  Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.7-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\python312\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\karan\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python312\lib\site-packages (from pandas) (2025.2)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.60.1-cp312-cp312-win_amd64.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\python312\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\python312\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\python312\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
Using cached matplotlib-3.10.7-cp312-cp312-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.60.1-cp312-cp312-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.4.9-cp312-cp312-win_amd64.whl (73 kB)
Installing collected packages: kiwisolver, fonttools, cycler, contourpy, pandas, matplotlib

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\Python312\\share'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import sys
!"{sys.executable}" -m pip install --user pandas matplotlib

Collecting pandas
  Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.7-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\python312\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\karan\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python312\lib\site-packages (from pandas) (2025.2)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: fonttools>=4.22.0 in c:\python312\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\python312\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\python312\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\python312\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\python312\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
Using cached matplotlib-3.10.7-cp312-cp312-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Installing collected packages: cycler, contourpy, pandas, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 matplotlib-3.10.7 pandas-2.3.3

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('flipkart_sales.csv', encoding='latin1')
df.rename(columns={'InvoiceNo':'OrderID','UnitPrice':'Price','Country':'City'}, inplace=True)
df.head()

,OrderID,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,City
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

,OrderID,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,City
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [ ]:
# === Flipkart sales quick dashboard (tables + plots + image files) ===
# Paste this whole cell and run it. It will:
# 1) Load flipkart_sales.csv
# 2) Show head() and a Top Products table
# 3) Plot Top Products (bar) and Daily Revenue (line)
# 4) Save the plots as dashboard_chart1.png and dashboard_chart2.png

# --- Imports & Notebook plotting setup ---
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
%matplotlib inline

# --- Load CSV (same folder as notebook) ---
csv_path = Path('flipkart_sales.csv')
df = pd.read_csv(csv_path, encoding='latin1', low_memory=False)

# --- Make column names easier to use (lowercase, no spaces) ---
df.columns = [c.strip().lower().replace(' ', '_') for c in df.columns]

# --- Try to resolve the most likely column names in your file ---
# Dates
for cand in ['invoicedate', 'invoice_date', 'order_date', 'date']:
    if cand in df.columns:
        date_col = cand
        break
else:
    date_col = None

# Quantity
for cand in ['quantity', 'qty']:
    if cand in df.columns:
        qty_col = cand
        break
else:
    qty_col = None

# Unit price / price per item
for cand in ['unitprice', 'unit_price', 'price']:
    if cand in df.columns:
        price_col = cand
        break
else:
    price_col = None

# Product identifier/name for grouping
for cand in ['description', 'product_name', 'stockcode', 'stock_code', 'item']:
    if cand in df.columns:
        prod_col = cand
        break
else:
    prod_col = None

# --- Parse dates if present ---
if date_col is not None:
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

# --- Compute Revenue ---
# Prefer revenue = quantity * unit price; otherwise look for a total column.
if qty_col is not None and price_col is not None:
    df['revenue'] = pd.to_numeric(df[qty_col], errors='coerce') * pd.to_numeric(df[price_col], errors='coerce')
elif 'revenue' not in df.columns:
    # fall back to any plausible total column name
    for cand in ['total', 'line_total', 'amount']:
        if cand in df.columns:
            df['revenue'] = pd.to_numeric(df[cand], errors='coerce')
            break
    else:
        df['revenue'] = pd.NA  # nothing available

# Drop rows that can't be used for plots
if date_col is not None:
    df = df.dropna(subset=[date_col])
if 'revenue' in df.columns:
    df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce')

# === TABLE 1: First few rows (preview) ===
display(df.head(10))

# === TABLE 2: Top 10 products by revenue (falls back to quantity if needed) ===
if prod_col is not None:
    agg_target = 'revenue' if 'revenue' in df.columns else (qty_col if qty_col is not None else None)
    if agg_target is not None:
        top_products = (df.groupby(prod_col, dropna=True)[agg_target]
                          .sum()
                          .sort_values(ascending=False)
                          .head(10)
                          .reset_index()
                          .rename(columns={prod_col: 'product', agg_target: 'value'}))
        display(top_products)
    else:
        top_products = None
else:
    top_products = None

# === CHART 1: Top 10 products (bar chart) ===
plt.figure(figsize=(10, 6))
if top_products is not None and not top_products.empty:
    # horizontal bar for readability
    plt.barh(top_products['product'][::-1], top_products['value'][::-1])
    y_label = 'Revenue' if 'revenue' in df.columns else 'Quantity'
    plt.xlabel(y_label)
    plt.ylabel('Product')
    plt.title(f'Top 10 Products by {y_label}')
else:
    # Fallback: distribution of unit price or price if product table unavailable
    if price_col is not None:
        plt.hist(pd.to_numeric(df[price_col], errors='coerce').dropna(), bins=30)
        plt.xlabel('Unit Price')
        plt.ylabel('Count')
        plt.title('Unit Price Distribution')
    else:
        plt.text(0.5, 0.5, 'No suitable columns for Top Products / Price histogram',
                 ha='center', va='center', transform=plt.gca().transAxes)
plt.tight_layout()
plt.savefig('dashboard_chart1.png', dpi=200, bbox_inches='tight')
plt.show()

# === CHART 2: Daily revenue over time (line chart) ===
plt.figure(figsize=(10, 5))
if date_col is not None and 'revenue' in df.columns and df['revenue'].notna().any():
    daily_rev = df.set_index(date_col)['revenue'].resample('D').sum()
    plt.plot(daily_rev.index, daily_rev.values)
    plt.xlabel('Date')
    plt.ylabel('Revenue')
    plt.title('Daily Revenue')
else:
    # Fallback: daily order count if revenue not available
    if date_col is not None:
        daily_cnt = df.set_index(date_col).resample('D').size()
        plt.plot(daily_cnt.index, daily_cnt.values)
        plt.xlabel('Date')
        plt.ylabel('Orders')
        plt.title('Daily Orders')
    else:
        plt.text(0.5, 0.5, 'No date column available for time series',
                 ha='center', va='center', transform=plt.gca().transAxes)
plt.tight_layout()
plt.savefig('dashboard_chart2.png', dpi=200, bbox_inches='tight')
plt.show()

print("Saved: dashboard_chart1.png, dashboard_chart2.png")

In [ ]:
# === Flipkart sales quick dashboard (tables + plots + image files) ===
# Paste this whole cell and run it. It will:
# 1) Load flipkart_sales.csv
# 2) Show head() and a Top Products table
# 3) Plot Top Products (bar) and Daily Revenue (line)
# 4) Save the plots as dashboard_chart1.png and dashboard_chart2.png

# --- Imports & Notebook plotting setup ---
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
%matplotlib inline

# --- Load CSV (same folder as notebook) ---
csv_path = Path('flipkart_sales.csv')
df = pd.read_csv(csv_path, encoding='latin1', low_memory=False)

# --- Make column names easier to use (lowercase, no spaces) ---
df.columns = [c.strip().lower().replace(' ', '_') for c in df.columns]

# --- Try to resolve the most likely column names in your file ---
# Dates
for cand in ['invoicedate', 'invoice_date', 'order_date', 'date']:
    if cand in df.columns:
        date_col = cand
        break
else:
    date_col = None

# Quantity
for cand in ['quantity', 'qty']:
    if cand in df.columns:
        qty_col = cand
        break
else:
    qty_col = None

# Unit price / price per item
for cand in ['unitprice', 'unit_price', 'price']:
    if cand in df.columns:
        price_col = cand
        break
else:
    price_col = None

# Product identifier/name for grouping
for cand in ['description', 'product_name', 'stockcode', 'stock_code', 'item']:
    if cand in df.columns:
        prod_col = cand
        break
else:
    prod_col = None

# --- Parse dates if present ---
if date_col is not None:
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

# --- Compute Revenue ---
# Prefer revenue = quantity * unit price; otherwise look for a total column.
if qty_col is not None and price_col is not None:
    df['revenue'] = pd.to_numeric(df[qty_col], errors='coerce') * pd.to_numeric(df[price_col], errors='coerce')
elif 'revenue' not in df.columns:
    # fall back to any plausible total column name
    for cand in ['total', 'line_total', 'amount']:
        if cand in df.columns:
            df['revenue'] = pd.to_numeric(df[cand], errors='coerce')
            break
    else:
        df['revenue'] = pd.NA  # nothing available

# Drop rows that can't be used for plots
if date_col is not None:
    df = df.dropna(subset=[date_col])
if 'revenue' in df.columns:
    df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce')

# === TABLE 1: First few rows (preview) ===
display(df.head(10))

# === TABLE 2: Top 10 products by revenue (falls back to quantity if needed) ===
if prod_col is not None:
    agg_target = 'revenue' if 'revenue' in df.columns else (qty_col if qty_col is not None else None)
    if agg_target is not None:
        top_products = (df.groupby(prod_col, dropna=True)[agg_target]
                          .sum()
                          .sort_values(ascending=False)
                          .head(10)
                          .reset_index()
                          .rename(columns={prod_col: 'product', agg_target: 'value'}))
        display(top_products)
    else:
        top_products = None
else:
    top_products = None

# === CHART 1: Top 10 products (bar chart) ===
plt.figure(figsize=(10, 6))
if top_products is not None and not top_products.empty:
    # horizontal bar for readability
    plt.barh(top_products['product'][::-1], top_products['value'][::-1])
    y_label = 'Revenue' if 'revenue' in df.columns else 'Quantity'
    plt.xlabel(y_label)
    plt.ylabel('Product')
    plt.title(f'Top 10 Products by {y_label}')
else:
    # Fallback: distribution of unit price or price if product table unavailable
    if price_col is not None:
        plt.hist(pd.to_numeric(df[price_col], errors='coerce').dropna(), bins=30)
        plt.xlabel('Unit Price')
        plt.ylabel('Count')
        plt.title('Unit Price Distribution')
    else:
        plt.text(0.5, 0.5, 'No suitable columns for Top Products / Price histogram',
                 ha='center', va='center', transform=plt.gca().transAxes)
plt.tight_layout()
plt.savefig('dashboard_chart1.png', dpi=200, bbox_inches='tight')
plt.show()

# === CHART 2: Daily revenue over time (line chart) ===
plt.figure(figsize=(10, 5))
if date_col is not None and 'revenue' in df.columns and df['revenue'].notna().any():
    daily_rev = df.set_index(date_col)['revenue'].resample('D').sum()
    plt.plot(daily_rev.index, daily_rev.values)
    plt.xlabel('Date')
    plt.ylabel('Revenue')
    plt.title('Daily Revenue')
else:
    # Fallback: daily order count if revenue not available
    if date_col is not None:
        daily_cnt = df.set_index(date_col).resample('D').size()
        plt.plot(daily_cnt.index, daily_cnt.values)
        plt.xlabel('Date')
        plt.ylabel('Orders')
        plt.title('Daily Orders')
    else:
        plt.text(0.5, 0.5, 'No date column available for time series',
                 ha='center', va='center', transform=plt.gca().transAxes)
plt.tight_layout()
plt.savefig('dashboard_chart2.png', dpi=200, bbox_inches='tight')
plt.show()

print("Saved: dashboard_chart1.png, dashboard_chart2.png")

In [ ]:
# === Flipkart sales quick dashboard (tables + plots + image files) ===
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import display  # ensures tables render in VS Code
%matplotlib inline

csv_path = Path('flipkart_sales.csv')
df = pd.read_csv(csv_path, encoding='latin1', low_memory=False)
df.columns = [c.strip().lower().replace(' ', '_') for c in df.columns]

# detect likely columns
for cand in ['invoicedate','invoice_date','order_date','date']:
    if cand in df.columns: date_col=cand; break
else: date_col=None
for cand in ['quantity','qty']:
    if cand in df.columns: qty_col=cand; break
else: qty_col=None
for cand in ['unitprice','unit_price','price']:
    if cand in df.columns: price_col=cand; break
else: price_col=None
for cand in ['description','product_name','stockcode','stock_code','item']:
    if cand in df.columns: prod_col=cand; break
else: prod_col=None

if date_col is not None:
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

# revenue
if qty_col and price_col:
    df['revenue'] = pd.to_numeric(df[qty_col], errors='coerce') * pd.to_numeric(df[price_col], errors='coerce')
elif 'revenue' not in df.columns:
    for cand in ['total','line_total','amount']:
        if cand in df.columns:
            df['revenue'] = pd.to_numeric(df[cand], errors='coerce'); break
    else:
        df['revenue'] = pd.NA

if date_col: df = df.dropna(subset=[date_col])

# TABLES
display(df.head(10))

if prod_col:
    target = 'revenue' if 'revenue' in df.columns else (qty_col if qty_col else None)
    if target:
        top_products = (df.groupby(prod_col, dropna=True)[target]
                          .sum().sort_values(ascending=False).head(10)
                          .reset_index().rename(columns={prod_col:'product', target:'value'}))
        display(top_products)
    else:
        top_products = None
else:
    top_products = None

# CHART 1
plt.figure(figsize=(10,6))
if top_products is not None and not top_products.empty:
    plt.barh(top_products['product'][::-1], top_products['value'][::-1])
    plt.xlabel('Revenue' if 'revenue' in df.columns else 'Quantity')
    plt.ylabel('Product'); plt.title('Top 10 Products')
else:
    if price_col:
        plt.hist(pd.to_numeric(df[price_col], errors='coerce').dropna(), bins=30)
        plt.xlabel('Unit Price'); plt.ylabel('Count'); plt.title('Unit Price Distribution')
    else:
        plt.text(0.5, 0.5, 'No suitable columns for product/price chart',
                 ha='center', va='center', transform=plt.gca().transAxes)
plt.tight_layout(); plt.savefig('dashboard_chart1.png', dpi=200, bbox_inches='tight'); plt.show()

# CHART 2
plt.figure(figsize=(10,5))
if date_col and 'revenue' in df.columns and df['revenue'].notna().any():
    daily_rev = df.set_index(date_col)['revenue'].resample('D').sum()
    plt.plot(daily_rev.index, daily_rev.values)
    plt.xlabel('Date'); plt.ylabel('Revenue'); plt.title('Daily Revenue')
elif date_col:
    daily_cnt = df.set_index(date_col).resample('D').size()
    plt.plot(daily_cnt.index, daily_cnt.values)
    plt.xlabel('Date'); plt.ylabel('Orders'); plt.title('Daily Orders')
else:
    plt.text(0.5, 0.5, 'No date column available for time series',
             ha='center', va='center', transform=plt.gca().transAxes)
plt.tight_layout(); plt.savefig('dashboard_chart2.png', dpi=200, bbox_inches='tight'); plt.show()

print("Saved: dashboard_chart1.png, dashboard_chart2.png")